topology: TORUS
topology_args: [10, 10]
topology_channels: 1
virtual_channels: 2
subtopology: NONE 
subnetwork: PHYSICAL
update_sequence: DEFAULT
buffer_depth: 8

min_packet_size: 8
max_packet_size: 8

flit_injection_rate: true
scale_with_nodes: false
packet_injection_rate: 0.05
probability_of_retransmission: 1

routing_algorithm: MESH_XY
selection_strategy: RANDOM
routing_table: UP_DOWN
routing_table_id_based: true

rnd_generator_seed: 0
report_progress: true
report_buffers: false
report_topology_graph: false
report_topology_graph_adjacency_matrix: false
report_routing_table: false
report_possible_routes: false
report_routes_stats: false
report_topology_sub_graph: false
report_topology_sub_graph_adjacency_matrix: false
report_sub_routing_table: false
report_cycle_result: false
report_flit_trace: false

clock_period_ps: 1000
reset_time: 1000
simulation_time: 10000
stats_warm_up_time: 300
traffic_distribution: TRAFFIC_RANDOM